### ISSUE TITLE
WI Windows Bug (same as UT)

### ISSUE THREAD

**Issue by ydoc5212** [biglocalnews/warn-scraper#202]
Traceback (most recent call last):
  File "C:\Users\Cody-DellXPS\WARN\warn\cli.py", line 67, in main
    runner.scrape(state)
  File "C:\Users\Cody-DellXPS\WARN\warn\runner.py", line 46, in scrape
    output_csv = state_mod.scrape(self.output_dir, self.working_dir)
  File "C:\Users\Cody-DellXPS\WARN\warn\scrapers\wi.py", line 54, in scrape
    writer.writerows(output_rows)
  File "c:\users\cody-dellxps\appdata\local\programs\python\python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 75-76: character maps to <undefined>

**Comment by palewire** [comment]
This scraper is now running fine for me. Since this ticket is more than six months old, I am going to close it. If you are still encountering the bug, please speak up. We can always reopen and address it.
