### ISSUE TITLE
Specifying data-dir fails on string conversion issue

### ISSUE THREAD

**Issue by chriszs** [biglocalnews/warn-scraper#405]
When I do:

```sh
warn-scraper CT --data-dir data
```

I get the following error in the logs:

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/warn/cli.py", line 80, in main
    runner.scrape(scrape)
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/warn/runner.py", line 52, in scrape
    data_path = state_mod.scrape(self.data_dir, self.cache_dir)
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/warn/scrapers/ct.py", line 82, in scrape
    data_path = data_dir / "ct.csv"
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```

Anecdotally also recall this happening on other states.

@palewire Avoiding this was why I was constructing the output path using string formation and later `Path`.

**Comment by palewire** [comment]
Sounds like a bug for sure!
