### ISSUE TITLE
Fix CA: Scraper is bugging out

### ISSUE THREAD

**Issue by palewire** [biglocalnews/warn-scraper#462]
From [today's scrapes](https://github.com/biglocalnews/warn-github-flow/runs/5564305344?check_suite_focus=true):

```
pipenv run python -m warn.cli ca -l DEBUG
2022-03-16 03:21:20,632 - warn.runner - Scraping ca
2022-03-16 03:21:20,633 - warn.scrapers.ca - Getting metadata for data files
2022-03-16 03:21:20,633 - warn.utils - Requesting https://edd.ca.gov/Jobs_and_Training/Layoff_Services_WARN.htm
2022-03-16 03:21:21,099 - warn.utils - Response code: 200
2022-03-16 03:21:23,932 - warn.cache - Requesting https://edd.ca.gov/Jobs_and_Training/warn/WARN_Report.xlsx
2022-03-16 03:21:23,932 - warn.utils - Requesting https://edd.ca.gov/Jobs_and_Training/warn/WARN_Report.xlsx
2022-03-16 03:21:24,211 - warn.utils - Response code: 200
2022-03-16 03:21:24,211 - warn.cache - Writing to data/warn-scraper/cache/ca/WARN_Report.xlsx
2022-03-16 03:21:24,297 - warn.scrapers.ca - One or more source data files have changed
2022-03-16 03:21:24,297 - warn.scrapers.ca - Extracting Excel data for current fiscal year
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/runpy.py", line [19](https://github.com/biglocalnews/warn-github-flow/runs/5564305344?check_suite_focus=true#step:7:19)7, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/runner/.local/share/virtualenvs/warn-github-flow-R1xICqqL/lib/python3.9/site-packages/warn/cli.py", line 79, in <module>
    main()
  File "/home/runner/.local/share/virtualenvs/warn-github-flow-R1xICqqL/lib/python3.9/site-packages/click/core.py", line 11[28](https://github.com/biglocalnews/warn-github-flow/runs/5564305344?check_suite_focus=true#step:7:28), in __call__
    return self.main(*args, **kwargs)
  File "/home/runner/.local/share/virtualenvs/warn-github-flow-R1xICqqL/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/runner/.local/share/virtualenvs/warn-github-flow-R1xICqqL/lib/python3.9/site-packages/click/core.py", line 1[39](https://github.com/biglocalnews/warn-github-flow/runs/5564305344?check_suite_focus=true#step:7:39)5, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/runner/.local/share/virtualenvs/warn-github-flow-R1xICqqL/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/runner/.local/share/virtualenvs/warn-github-flow-R1xICqqL/lib/python3.9/site-packages/warn/cli.py", line 75, in main
    runner.scrape(scrape)
  File "/home/runner/.local/share/virtualenvs/warn-github-flow-R1xICqqL/lib/python3.9/site-packages/warn/runner.py", line [52](https://github.com/biglocalnews/warn-github-flow/runs/5564305344?check_suite_focus=true#step:7:52), in scrape
    data_path = state_mod.scrape(self.data_dir, self.cache_dir)
  File "/home/runner/.local/share/virtualenvs/warn-github-flow-R1xICqqL/lib/python3.9/site-packages/warn/scrapers/ca.py", line 65, in scrape
    excel_data = _extract_excel_data(wb_path)
  File "/home/runner/.local/share/virtualenvs/warn-github-flow-R1xICqqL/lib/python3.9/site-packages/warn/scrapers/ca.py", line 174, in _extract_excel_data
    "address": row[12].value.strip(),
AttributeError: 'NoneType' object has no attribute 'strip'
make: *** [Makefile:71: scrape] Error 1
```

**Comment by palewire** [comment]
Fixed by #463
