### ISSUE TITLE
Fix CO: Scraper crashing

### ISSUE THREAD

**Issue by palewire** [biglocalnews/warn-scraper#500]
Seen [here](https://github.com/biglocalnews/warn-github-flow/actions/runs/3564571489/jobs/5988691763)

```
pipenv run python -m warn.cli co -l DEBUG
2022-11-28 12:07:40,073 - warn.runner - Scraping co
2022-11-28 12:07:40,073 - warn.utils - Requesting https://cdle.colorado.gov/employers/layoff-separations/layoff-warn-list
2022-11-28 12:07:40,238 - warn.utils - Response code: 403
2022-11-28 12:07:40,238 - warn.cache - Writing to cache data/warn-scraper/cache/co/main/source.html
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/runner/.local/share/virtualenvs/warn-github-flow-R1xICqqL/lib/python3.9/site-packages/warn/cli.py", line 79, in <module>
    main()
  File "/home/runner/.local/share/virtualenvs/warn-github-flow-R1xICqqL/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/runner/.local/share/virtualenvs/warn-github-flow-R1xICqqL/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/runner/.local/share/virtualenvs/warn-github-flow-R1xICqqL/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/runner/.local/share/virtualenvs/warn-github-flow-R1xICqqL/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/runner/.local/share/virtualenvs/warn-github-flow-R1xICqqL/lib/python3.9/site-packages/warn/cli.py", line 75, in main
    runner.scrape(scrape)
  File "/home/runner/.local/share/virtualenvs/warn-github-flow-R1xICqqL/lib/python3.9/site-packages/warn/runner.py", line [52](https://github.com/biglocalnews/warn-github-flow/actions/runs/3564571489/jobs/5988691763#step:4:55), in scrape
    data_path = state_mod.scrape(self.data_dir, self.cache_dir)
  File "/home/runner/.local/share/virtualenvs/warn-github-flow-R1xICqqL/lib/python3.9/site-packages/warn/scrapers/co.py", line 43, in scrape
    current_link = str(soup.find("a", class_="btn btn-primary")).split('"')[3]
IndexError: list index out of range
make: *** [Makefile:[71](https://github.com/biglocalnews/warn-github-flow/actions/runs/3564571489/jobs/5988691763#step:4:74): scrape] Error 1
Error: Process completed with exit code 2.
```

**Comment by palewire** [comment]
I can't recreate this bug in the main branch. We'll keep an eye on it with future scrapes via the bot.
